// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/mypage/github/repo/[name].tsx";
import * as $1 from "./pages/mypage/github.tsx";
import * as $2 from "./pages/login/github/callback.ts";
import * as $3 from "./pages/login/github/auth.ts";
import * as $4 from "./pages/index.tsx";
import * as $5 from "./pages/api/github/repos.ts";
import * as $6 from "./pages/api/github/pulls/[repo_name].tsx";

const routes = {
  pages: {
    "./pages/mypage/github/repo/[name].tsx": $0,
    "./pages/mypage/github.tsx": $1,
    "./pages/login/github/callback.ts": $2,
    "./pages/login/github/auth.ts": $3,
    "./pages/index.tsx": $4,
    "./pages/api/github/repos.ts": $5,
    "./pages/api/github/pulls/[repo_name].tsx": $6,
  },
  baseUrl: import.meta.url,
};

export default routes;
